### ISSUE TITLE
error linting cant open glualint.json

### ISSUE THREAD

**Issue by LiamTownsley** [TASSIA710/action-glua-lint#6] opened 2021-03-29 09:39 UTC
Linting /home/runner/work/PoliceRP/PoliceRP/...
> ./glualint /home/runner/work/PoliceRP/PoliceRP/ --config /home/runner/work/_actions/TASSIA710/action-glua-lint/v1.1.1/dependencies/glualint.json
./glualint: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory
Error: Error: Command failed: ./glualint /home/runner/work/PoliceRP/PoliceRP/ --config /home/runner/work/_actions/TASSIA710/action-glua-lint/v1.1.1/dependencies/glualint.json
./glualint: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory

**Comment by talemke** [comment] 2021-03-29 18:16
Hi,

thanks for informing me of this issue. It was caused by an old version of GLuaFixer to depend on `libffi.so.6`, which broke when GitHub updated actions to use Ubuntu 20 by default.

This issue has been fixed in **v1.1.3** of `action-glua-lint` so make sure to update your workflow file accordingly.

As an alternative, you can manually tell GitHub to use Ubuntu 18 by specifying `runs-on: ubuntu-18.04`.

**Closed as completed by talemke** 2021-03-29 18:16 UTC
Labels: bug
